In [1]:
#Reshape From 1-D to 2-D

import numpy as np # type: ignore

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
#Reshape From 1-D to 3-D

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

"""

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) creates a 1D NumPy array.

arr.reshape(2, 4) reshapes the 1D array into a 2D array with 2 rows and 4 columns. Importantly, reshape in NumPy typically returns a view of the original array, not a copy.

print(arr.reshape(2, 4).base) checks the base of the reshaped array. Since the reshaped array is a view of the original arr, the .base attribute should point to the original array.


"""

[1 2 3 4 5 6 7 8]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

"""

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) creates a 1D NumPy array with 8 elements.

newarr = arr.reshape(2, 2, -1) reshapes the array into a 3D array. The dimensions specified are (2, 2, -1). The -1 in the reshape function allows NumPy to automatically calculate the size of that dimension based on the size of the original array and the other specified dimensions.

The first dimension is 2, which means there will be 2 sub-arrays.
The second dimension is also 2, so each sub-array will have 2 rows.
The -1 for the third dimension indicates that NumPy should figure out how many columns are needed based on the total number of elements (which is 8 in this case).
Since the total number of elements is 8, and the first two dimensions account for 2 * 2 = 4 elements, the third dimension must be 8 / 4 = 2 elements.

Therefore, the array will be reshaped into a 2x2x2 3D array.

print(newarr) prints the reshaped 3D array.

"""

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


"""
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

"""

[1 2 3 4 5 6]


'\nFlattening array means converting a multidimensional array into a 1D array.\n\nWe can use reshape(-1) to do this.\n\n'