In [1]:
import numpy as np # type: ignore

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [ ]:
import numpy as np

arr = np.array([6, 17, 8, 9])

x = np.searchsorted(arr, 17)

print(x)


In [4]:
import numpy as np

arr = np.array([6, 17, 85, 9])

x = np.searchsorted(arr, 17, side='right')

print(x)


2


In [5]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
